#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
#include <list>
#include <deque>
#include <algorithm>
#include <numeric>
#include <fstream>
#include <sstream>
#include <random>
#include <cstdlib>
#include <ctime>
#include <chrono>

using std::invalid_argument;
using std::istringstream;
using std::ifstream;
using std::ofstream;
using std::string;
using std::vector;
using std::list;
using std::deque;
using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::right;
using std::setw;
using std::setprecision;
using std::copy;
using std::fixed;
using std::srand;
using std::accumulate;
using std::sort;
using std::getline;
using std::to_string;
using std::remove_if;
