#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
#include <algorithm>
#include <numeric>
#include <random>

using std::string;
using std::vector;
using std::invalid_argument;
using std::mt19937;
using std::uniform_int_distribution;
using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::setw;
using std::setprecision;
using std::copy;
using std::fixed;
using std::srand;
using std::accumulate;
using std::sort;