#include <iostream>
#include <iomanip>
#include <string>
#include <vector>
#include <algorithm>
#include <numeric>
#include <fstream>
#include <sstream>
#include <random>

using std::invalid_argument;
using std::istringstream;
using std::ifstream;
using std::ofstream;
using std::string;
using std::vector;
using std::cout;
using std::cin;
using std::endl;
using std::left;
using std::setw;
using std::setprecision;
using std::copy;
using std::fixed;
using std::srand;
using std::accumulate;
using std::sort;
using std::getline;